export const UPDATE_COST_SUCCESS = 'UPDATE_COST_SUCCESS';
export const UPDATE_TESTFLIGHT_SUCCESS = 'UPDATE_TESTFLIGHT_SUCCESS';
export const UPDATE_FLIGHT_CHANCE_SUCCESS = 'UPDATE_FLIGHT_CHANCE_SUCESS';
export const UPDATE_FUEL_AMOUNT_SUCCESS = 'UPDATE_FUEL_AMOUNT_SUCCESS';
